// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIn2OFatW1l_H8UWwZL7ATPnCc2H2YNzg',
    appId: '1:1069274854514:web:0cb21bd7e7793db942feeb',
    messagingSenderId: '1069274854514',
    projectId: 'flutter-db-ad6ab',
    authDomain: 'flutter-db-ad6ab.firebaseapp.com',
    storageBucket: 'flutter-db-ad6ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4gB-1jYhzL0-TBkgKc4iU2MJ4TO027Yg',
    appId: '1:1069274854514:android:9bbeca567aee209842feeb',
    messagingSenderId: '1069274854514',
    projectId: 'flutter-db-ad6ab',
    storageBucket: 'flutter-db-ad6ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jDKz7jDbjpWHHBedEz2ALbizoKpoN1g',
    appId: '1:1069274854514:ios:453a09a84687c83b42feeb',
    messagingSenderId: '1069274854514',
    projectId: 'flutter-db-ad6ab',
    storageBucket: 'flutter-db-ad6ab.firebasestorage.app',
    iosBundleId: 'com.example.dbFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jDKz7jDbjpWHHBedEz2ALbizoKpoN1g',
    appId: '1:1069274854514:ios:453a09a84687c83b42feeb',
    messagingSenderId: '1069274854514',
    projectId: 'flutter-db-ad6ab',
    storageBucket: 'flutter-db-ad6ab.firebasestorage.app',
    iosBundleId: 'com.example.dbFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIn2OFatW1l_H8UWwZL7ATPnCc2H2YNzg',
    appId: '1:1069274854514:web:ea528dab7a2cdbfe42feeb',
    messagingSenderId: '1069274854514',
    projectId: 'flutter-db-ad6ab',
    authDomain: 'flutter-db-ad6ab.firebaseapp.com',
    storageBucket: 'flutter-db-ad6ab.firebasestorage.app',
  );
}
